<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <!-- Global dotnet tool packaging -->
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>sharpfetch</ToolCommandName>
    <PackageId>SharpFetch</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpFetch.Core\SharpFetch.Core.csproj" />
    <ProjectReference Include="..\SharpFetch.UI\SharpFetch.UI.csproj" />
  </ItemGroup>

</Project>
